export const ActionTypes = {
  LOGIN : "LOGIN",
  LOGOUT : "LOGOUT",
  SET_ALERT : "SET_ALERT",
  CLEAR_ALERT : "CLEAR_ALERT",
  GET_USER_DETAILS : "GET_USER_DETAILS",
  STUDENT_REGISTER : "STUDENT_REGISTER",
  GET_ALL_SUBJECT : "GET_ALL_SUBJECTS",
  SEARCH_QUESTION : "SEARCH_QUESTION",
  CHANGE_QUESTION_STATUS : "CHANGE_QUESTION_STATUS",
  VIEW_QUESTION : 'VIEW_QUESTION',
  GET_BACK_TO_SEARCH : "GET_BACK_TO_SEARCH",
  UPDATE_QUESTION : "UPDATE_QUESTION"
};