export const ActionTypes = {
  LOGIN : "LOGIN",
  LOGOUT : "LOGOUT",
  DASHBOARD_COUNT : "DASHBOARD_COUNT",
  GET_ALL_TEACHER : "GET_ALL_TEACHER",
  REMOVE_USER : "REMOVE_USER",
  UNBLOCK_USER : "UNBLOCK_USER",
  GET_ALL_STUDENT : "GET_ALL_STUDENT",
  GET_ALL_SUBJECT : "GET_ALL_SUBJECT"
};